version: '3.3'

services:
    mysql:
        image: mysql:8.0.23
        container_name: mat-sql
        command: '--skip-name-resolve'
        restart: always
        ports:
            - 3307:3306
        networks:
            - mat-backend
        environment:
            - "MYSQL_DATABASE=${MYSQL_DATABASE}"
            - "MYSQL_USERNAME=${MYSQL_USERNAME}"
            - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
            - "MYSQL_HOST=${MYSQL_HOST}"
            - "MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}"

    redis:
        image: redis:6.2
        container_name: mat-redis
        depends_on:
            - mysql
        ports:
            - 6379:6379
        networks:
            - mat-backend

    node:
        container_name: mat-node
        command: 'npm run start:docker'
        depends_on:
            - mysql
            - redis
        build:
            context: ./
            dockerfile: ./docker/Dockerfile
        networks:
            - mat-backend
            - mat-proxy_mat-nginx-network
        ports:
            - 6969:6969
            - 3000:3000
            - 3040:3040
        links:
            - mysql
            - redis
        volumes:
            - .:/usr/src/app:delegated
            - /usr/src/app/node_modules
        environment: 
            - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
            - "MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}"
            - MYSQL_HOST=mysql
            - REDIS_HOST=redis

    nginx:
        image: nginx:alpine
        container_name: mat-node-nginx
        restart: always
        networks:
            - mat-backend
            - mat-proxy_mat-nginx-network
        depends_on:
            - node
            - mysql
            - redis
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/certs:/etc/nginx/certs:ro
            - ./:/opt/html
        ports:
            - 8001:443
        environment:
            - VIRTUAL_HOST=node.app
            - VIRTUAL_HOST=8001
        links:
            - node:node

networks:
    mat-backend:
    mat-proxy_mat-nginx-network:
        external: true
